### ISSUE TITLE
Unable to use cloud bank due to merge error

### ISSUE THREAD

**Issue by ossiesf** [ccsf-math-108/materials-fa24#1]
I am receiving a merge error when the cloud service attempts to pull the git repo and launch Jupyter.

As a work around, I'm just using the info as provided on GitHub itself.

This is the output:

> >$ git fetch
> $ git reset --mixed
> $ git -c user.email=nbgitpuller@nbgitpuller.link -c user.name=nbgitpuller merge -Xours origin/main
> fatal: refusing to merge unrelated histories
> Traceback (most recent call last):
> File "/srv/conda/envs/notebook/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
>     self.run()
> File "/srv/conda/envs/notebook/lib/python3.11/threading.py", line 982, in run
>     self._target(*self._args, **self._kwargs)
> File "/srv/conda/envs/notebook/lib/python3.11/site-packages/nbgitpuller/handlers.py", line 99, in pull
>     raise e
> File "/srv/conda/envs/notebook/lib/python3.11/site-packages/nbgitpuller/handlers.py", line 93, in pull
>     for line in gp.pull():
> File "/srv/conda/envs/notebook/lib/python3.11/site-packages/nbgitpuller/pull.py", line 144, in pull
>     yield from self.update()
> File "/srv/conda/envs/notebook/lib/python3.11/site-packages/nbgitpuller/pull.py", line 344, in update
>     yield from self.merge()
> File "/srv/conda/envs/notebook/lib/python3.11/site-packages/nbgitpuller/pull.py", line 273, in merge
>     for line in execute_cmd([
> File "/srv/conda/envs/notebook/lib/python3.11/site-packages/nbgitpuller/pull.py", line 48, in execute_cmd
>     raise subprocess.CalledProcessError(ret, cmd)
> subprocess.CalledProcessError: Command '['git', '-c', 'user.email=nbgitpuller@nbgitpuller.link', '-c', 'user.name=nbgitpuller', 'merge', '-Xours', 'origin/main']' returned non-zero exit status 128.

**Comment by shawnwiggins** [comment]
Thanks for posting this issue @ossiesf. I removed your `materials-fa24` folder which had a conflict with the current version. You should be able to open the links from Canvas successfully now. Let me or your instructor know if you are still having an issue. Once, I know this is resolved, I'll close this issue.
